[project]
version = "2.0.2"
readme = "README.md"
name = "antimatter-shared-fs"
description = "Filesystem shared protocol components for Antimatter"
dependencies = [
    "antimatter-shared-protocol",
    "antimatter-shared-config"
]

[tool.uv.sources]
antimatter-shared-protocol = { workspace = true }
antimatter-shared-config = { workspace = true }


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
